title: data analysis project
description: jekyll site for project
theme: just-the-docs

url: https://johnargentino.github.io/test_site

aux_links:
  Template Repository: https://github.com/johnargentino/test_site
